### ISSUE TITLE
In the Module tutorial, same data were printed in training and validation.

### ISSUE THREAD

**Issue by daslu** [Chouffe/mxnet-clj-tutorials#2]
Thank you for this beautiful project!

The following point in the tutorial is a bit confusing:

https://github.com/Chouffe/mxnet-clj-tutorials/blob/master/src/mxnet_clj_tutorials/module.clj#L70
It looks like a typo in the example outputs put in comments -- not a bug in the code.

**Comment by Chouffe** [comment]
Thanks for opening this issue :) I will take a look soon.
